runtime: php
env: flex

beta_settings:
  cloud_sql_instances: "dientoandammaynhom6-293515:asia-southeast1:thegioididongdb"

runtime_config:
  document_root: wordpress

env_variables:
  WHITELIST_FUNCTIONS: escapeshellarg,escapeshellcmd,exec,pclose,popen,shell_exec,phpversion,php_uname
